//! Build script that parses `ebml_matroska.xml` and generates a compile-time
//! whitelist of EBML element IDs that are WebM-compatible.
//!
//! Elements marked with `<extension type="webmproject.org" webm="1"/>` in the
//! spec XML are considered WebM-compatible. The generated file lives at
//! `$OUT_DIR/webm_whitelist.rs` and is `include!`-d from the runtime code.

use std::env;
use std::fs;
use std::io::Write;
use std::path::Path;

fn main() {
    let xml_path = Path::new("src/sink/util/ebml_matroska.xml");
    println!("cargo:rerun-if-changed={}", xml_path.display());

    let xml_content = fs::read_to_string(xml_path)
        .expect("Failed to read ebml_matroska.xml");

    let mut webm_elements = parse_webm_elements(&xml_content);

    // EBML core elements from RFC 8794 — not in the Matroska schema XML but
    // always required for a valid EBML stream. Must be whitelisted so the
    // filter doesn't void out the EBML header.
    let ebml_core_elements: &[(&str, u32)] = &[
        ("EBML",                0x1A45DFA3),
        ("EBMLVersion",         0x4286),
        ("EBMLReadVersion",     0x42F7),
        ("EBMLMaxIDLength",     0x42F2),
        ("EBMLMaxSizeLength",   0x42F3),
        ("DocType",             0x4282),
        ("DocTypeVersion",      0x4287),
        ("DocTypeReadVersion",  0x4285),
        ("CRC-32",              0xBF),
        ("Void",                0xEC),
    ];
    for &(name, id) in ebml_core_elements {
        webm_elements.push((name.to_string(), id));
    }

    // Sort by element ID for binary search at runtime
    webm_elements.sort_by_key(|&(_, id)| id);

    // Generate the Rust source file
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let out_path = Path::new(&out_dir).join("webm_whitelist.rs");
    let mut out_file = fs::File::create(&out_path)
        .expect("Failed to create webm_whitelist.rs");

    writeln!(out_file, "// AUTO-GENERATED by build.rs from ebml_matroska.xml — do not edit!").unwrap();
    writeln!(out_file, "//").unwrap();
    writeln!(out_file, "// Contains the EBML element IDs that are WebM-compatible,").unwrap();
    writeln!(out_file, "// i.e. elements marked with <extension type=\"webmproject.org\" webm=\"1\"/>.").unwrap();
    writeln!(out_file, "// Sorted by ID for binary search lookup.").unwrap();
    writeln!(out_file).unwrap();
    writeln!(out_file, "/// Number of WebM-whitelisted element IDs.").unwrap();
    writeln!(out_file, "pub const WEBM_ELEMENT_COUNT: usize = {};", webm_elements.len()).unwrap();
    writeln!(out_file).unwrap();
    writeln!(out_file, "/// Sorted array of (element_name, element_id) for all WebM-compatible EBML elements.").unwrap();
    writeln!(out_file, "pub const WEBM_ELEMENT_IDS: [(&str, u32); {}] = [", webm_elements.len()).unwrap();
    for (name, id) in &webm_elements {
        writeln!(out_file, "    (\"{}\", 0x{:X}),", name, id).unwrap();
    }
    writeln!(out_file, "];").unwrap();
    writeln!(out_file).unwrap();
    writeln!(out_file, "/// Check whether a given EBML element ID is WebM-compatible.").unwrap();
    writeln!(out_file, "/// Uses binary search on the sorted whitelist.").unwrap();
    writeln!(out_file, "pub const fn is_webm_element(id: u32) -> bool {{").unwrap();
    writeln!(out_file, "    let mut lo = 0usize;").unwrap();
    writeln!(out_file, "    let mut hi = WEBM_ELEMENT_IDS.len();").unwrap();
    writeln!(out_file, "    while lo < hi {{").unwrap();
    writeln!(out_file, "        let mid = lo + (hi - lo) / 2;").unwrap();
    writeln!(out_file, "        let mid_id = WEBM_ELEMENT_IDS[mid].1;").unwrap();
    writeln!(out_file, "        if mid_id == id {{").unwrap();
    writeln!(out_file, "            return true;").unwrap();
    writeln!(out_file, "        }} else if mid_id < id {{").unwrap();
    writeln!(out_file, "            lo = mid + 1;").unwrap();
    writeln!(out_file, "        }} else {{").unwrap();
    writeln!(out_file, "            hi = mid;").unwrap();
    writeln!(out_file, "        }}").unwrap();
    writeln!(out_file, "    }}").unwrap();
    writeln!(out_file, "    false").unwrap();
    writeln!(out_file, "}}").unwrap();

    eprintln!(
        "cargo:warning=Generated WebM whitelist with {} elements",
        webm_elements.len()
    );

    // Also collect master (container) element IDs — needed so the filter
    // knows whether to recurse into an element's children or pass through
    // its raw data payload.
    let mut master_elements = parse_master_elements(&xml_content);
    // EBML and Segment are master elements from RFC 8794
    master_elements.push(("EBML".to_string(), 0x1A45DFA3));
    master_elements.sort_by_key(|&(_, id)| id);
    master_elements.dedup_by_key(|e| e.1);

    writeln!(out_file).unwrap();
    writeln!(out_file, "/// Number of master (container) element IDs.").unwrap();
    writeln!(out_file, "pub const MASTER_ELEMENT_COUNT: usize = {};", master_elements.len()).unwrap();
    writeln!(out_file).unwrap();
    writeln!(out_file, "/// Sorted array of master element IDs (elements whose payload contains child elements).").unwrap();
    writeln!(out_file, "pub const MASTER_ELEMENT_IDS: [(&str, u32); {}] = [", master_elements.len()).unwrap();
    for (name, id) in &master_elements {
        writeln!(out_file, "    (\"{}\", 0x{:X}),", name, id).unwrap();
    }
    writeln!(out_file, "];").unwrap();
    writeln!(out_file).unwrap();
    writeln!(out_file, "/// Check whether a given EBML element ID is a master (container) element.").unwrap();
    writeln!(out_file, "pub const fn is_master_element(id: u32) -> bool {{").unwrap();
    writeln!(out_file, "    let mut lo = 0usize;").unwrap();
    writeln!(out_file, "    let mut hi = MASTER_ELEMENT_IDS.len();").unwrap();
    writeln!(out_file, "    while lo < hi {{").unwrap();
    writeln!(out_file, "        let mid = lo + (hi - lo) / 2;").unwrap();
    writeln!(out_file, "        let mid_id = MASTER_ELEMENT_IDS[mid].1;").unwrap();
    writeln!(out_file, "        if mid_id == id {{").unwrap();
    writeln!(out_file, "            return true;").unwrap();
    writeln!(out_file, "        }} else if mid_id < id {{").unwrap();
    writeln!(out_file, "            lo = mid + 1;").unwrap();
    writeln!(out_file, "        }} else {{").unwrap();
    writeln!(out_file, "            hi = mid;").unwrap();
    writeln!(out_file, "        }}").unwrap();
    writeln!(out_file, "    }}").unwrap();
    writeln!(out_file, "    false").unwrap();
    writeln!(out_file, "}}").unwrap();

    eprintln!(
        "cargo:warning=Generated master element list with {} elements",
        master_elements.len()
    );
}

/// Parse the EBML Matroska schema XML and return all WebM-compatible elements
/// as `(name, id)` pairs.
///
/// Strategy: We find all top-level `<element ...>` blocks in the schema.
/// Each such block is either self-closing (`<element ... />`) or has a body
/// that ends with `</element>`. We extract `name` and `id` attributes from
/// the opening tag, then check if the block contains a child
/// `<extension type="webmproject.org" webm="1"/>`.
fn parse_webm_elements(xml: &str) -> Vec<(String, u32)> {
    let mut result = Vec::new();

    for (name, id_str, _type_attr, full_block) in iter_elements(xml) {
        let is_webm = full_block.contains(r#"type="webmproject.org" webm="1""#);
        if is_webm {
            let id_hex = id_str.trim_start_matches("0x").trim_start_matches("0X");
            if let Ok(id) = u32::from_str_radix(id_hex, 16) {
                result.push((name.to_string(), id));
            }
        }
    }

    result
}

/// Parse the EBML Matroska schema XML and return all master (container) elements
/// as `(name, id)` pairs.
fn parse_master_elements(xml: &str) -> Vec<(String, u32)> {
    let mut result = Vec::new();

    for (name, id_str, type_attr, _full_block) in iter_elements(xml) {
        if type_attr.as_deref() == Some("master") {
            let id_hex = id_str.trim_start_matches("0x").trim_start_matches("0X");
            if let Ok(id) = u32::from_str_radix(id_hex, 16) {
                result.push((name.to_string(), id));
            }
        }
    }

    result
}

/// Iterate over all `<element ...>` blocks in the schema XML.
/// Returns `(name, id_str, type_attr, full_block_str)` tuples.
fn iter_elements(xml: &str) -> Vec<(String, String, Option<String>, String)> {
    let mut result = Vec::new();
    let mut search_from = 0;

    loop {
        let tag_start = match xml[search_from..].find("<element ") {
            Some(pos) => search_from + pos,
            None => break,
        };

        let after_tag = &xml[tag_start..];

        let gt_pos = match after_tag.find('>') {
            Some(pos) => pos,
            None => break,
        };

        let opening_tag = &after_tag[..=gt_pos];
        let is_self_closing = opening_tag.ends_with("/>");

        let name = extract_attr(opening_tag, "name");
        let id_str = extract_attr(opening_tag, "id");
        let type_attr = extract_attr(opening_tag, "type");

        let block_end;
        if is_self_closing {
            block_end = tag_start + gt_pos + 1;
        } else {
            let after_open = tag_start + gt_pos + 1;
            match xml[after_open..].find("</element>") {
                Some(pos) => {
                    block_end = after_open + pos + "</element>".len();
                }
                None => {
                    search_from = tag_start + gt_pos + 1;
                    continue;
                }
            }
        }

        let full_block = &xml[tag_start..block_end];

        if let (Some(name), Some(id_str)) = (name, id_str) {
            result.push((
                name.to_string(),
                id_str.to_string(),
                type_attr.map(|s| s.to_string()),
                full_block.to_string(),
            ));
        }

        search_from = block_end;
    }

    result
}

/// Extract an XML attribute value from a tag string.
fn extract_attr<'a>(tag: &'a str, attr_name: &str) -> Option<&'a str> {
    let search = format!("{}=\"", attr_name);
    let start = tag.find(&search)? + search.len();
    let rest = &tag[start..];
    let end = rest.find('"')?;
    Some(&rest[..end])
}

